name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

  workflow_dispatch:
    inputs:
      filename:
        description: 'Name of the image file'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access files
      - name: Checkout repository
        uses: actions/checkout@v2

      # Fetch configuration from GitHub API (example for accessing a config file)
      - name: Fetch configuration from GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Securely use the token stored in secrets
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/Social-Joint/designEmailSignature/contents/config.json

 
      # Set dynamic image filename (from the input passed to the workflow)
      - name: Set dynamic image filename
        run: |
          echo "IMAGE_FILENAME=${{ github.event.inputs.filename }}" >> $GITHUB_ENV
          echo "The dynamic image filename is: $IMAGE_FILENAME"  # Debugging the dynamic filename

      # Ensure the 'uploads' folder exists (if it doesn't already)
      - name: Create 'uploads' folder if it doesn't exist
        run: |
          mkdir -p uploads

    # Debugging Step: Verify that the image file exists
      - name: Check if image file exists
        run: |
          IMAGE_PATH="uploads/${{ env.IMAGE_FILENAME }}"
          echo "Checking for image file: $IMAGE_PATH"
          if [ ! -f "$IMAGE_PATH" ]; then
            echo "Error: File $IMAGE_PATH not found!"
            exit 1
          fi
 
      # Debugging the URL and Path
      - name: Debug URL and Path
        run: |
          echo "Repository URL: https://api.github.com/repos/Social-Joint/designEmailSignature/contents/uploads/${{ env.IMAGE_FILENAME }}"
          echo "Uploading to: uploads/${{ env.IMAGE_FILENAME }}"


     # Upload image to the 'uploads' folder in the repository
      - name: Upload image to the uploads folder
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Securely use the token stored in secrets
        run: |
          IMAGE_PATH="uploads/${{ env.IMAGE_FILENAME }}"  # Define the image file path
          
          # Check if the image file exists
          if [ ! -f "$IMAGE_PATH" ]; then
            echo "Error: File $IMAGE_PATH not found!"
            exit 1
          fi

          # Base64 encode the image file content
          IMAGE_CONTENT=$(base64 -w 0 "$IMAGE_PATH")

          # Debugging Step: Check the encoded content (optional)
          echo "Encoded content: $IMAGE_CONTENT"

          # Use the GitHub API to upload the image to the 'uploads' folder
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"message": "Upload dynamic image", "content": "'$IMAGE_CONTENT'", "path": "uploads/'${{ env.IMAGE_FILENAME }}'", "branch": "main"}' \
            https://api.github.com/repos/Social-Joint/designEmailSignature/contents/uploads/${{ env.IMAGE_FILENAME }}


      # Deploy to GitHub Pages (assuming you want to deploy the build folder)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}  # Use GITHUB_TOKEN to authenticate
          publish_dir: ./build  # Directory to deploy (make sure you have the correct path)
