name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access files
      - name: Checkout repository
        uses: actions/checkout@v2

      # Upload image to the 'uploads' folder
      - name: Upload image to the uploads folder
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Securely use the token stored in secrets
        run: |
          # Base64 encode the image file you want to upload (e.g., 'image.jpg')
          # Ensure the image file is in the repository root or adjust the path accordingly
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"message": "Upload image", "content": "$(base64 -w 0 image.jpg)", "path": "uploads/image.jpg", "branch": "main"}' \
            https://api.github.com/repos/Social-Joint/designEmailSignature/contents/uploads/image.jpg

      # Delete image from the 'uploads' folder
      - name: Delete image from the uploads folder
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Securely use the token stored in secrets
        run: |
          # Fetch the sha of the file you want to delete from the 'uploads' folder
          sha=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/Social-Joint/designEmailSignature/contents/uploads/image.jpg | jq -r .sha)
          
          # Delete the image file using the sha
          curl -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"message": "Delete image", "sha": "'$sha'"}' \
            https://api.github.com/repos/Social-Joint/designEmailSignature/contents/uploads/image.jpg

      # Deploy to GitHub Pages (assuming you want to deploy the build folder)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}  # Use GITHUB_TOKEN to authenticate
          publish_dir: ./build  # Directory to deploy (make sure you have the correct path)
